### ISSUE TITLE
Synology daemon error

### ISSUE THREAD

**Issue by tylerepperson** [beatkind/watchtower#117]
### Describe the bug

When installing on a Synology I get this error:

`Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43`

### Steps to reproduce

Installed via Docker Compose with this yml:

```
version: "3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=${DISCORD}
      - WATCHTOWER_MONITOR_ONLY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

### Environment

- Platform
- Architecture
- Docker Version

### Your logs

```text
Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43
```

### Additional context

I've added '- DOCKER_API_VERSION=1.43' in the meantime as I saw from the other post about increasing the API and it works for now.
