### ISSUE TITLE
Failed to handle container that is built from build

### ISSUE THREAD

**Issue by janusn** [beatkind/watchtower#125]
### Describe the bug

I have a container caddy that requires additional components from official plugins. Hence the container requires build steps. Watchwower reported error on handling it even a label `LABEL com.centurylinklabs.watchtower.monitor-only="true"` was added to the compose file.

### Steps to reproduce

1. $ docker compose -f '[path/to/caddy/compose.yaml]' up -d
2. $ docker compose - '[path/to/watchtower/compose.yaml]' up -d
3. wait until the cronjob of watchtower run or add an env. variable 'WATCHTOWER_RUN_ONCE=true'
4. watchtower logs the error.

### Expected behavior

Watchertower executes without errors and report the image updates if any.

### Environment

- Platform Debian version 12 (bookworm)
- Architecture amd64
- Docker Version version 28.0.2, build 0442a73

### Your logs

```text
time="2025-03-22T18:26:02Z" level=warning msg="Could not do a head request for \"caddy-caddy:latest\", falling back to regular pull." container=/caddy image="caddy-caddy:latest"
time="2025-03-22T18:26:02Z" level=warning msg="Reason: registry responded to head request with \"401 Unauthorized\", auth: \"Bearer realm=\\\"https://auth.docker.io/token\\\",service=\\\"registry.docker.io\\\",scope=\\\"repository:library/caddy-caddy:pull\\\",error=\\\"insufficient_scope\\\"\"" container=/caddy image="caddy-caddy:latest"
time="2025-03-22T18:26:03Z" level=info msg="Unable to update container \"/caddy\": Error response from daemon: pull access denied for caddy-caddy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. Proceeding to next."
time="2025-03-22T18:26:26Z" level=info msg="Found new nicolargo/glances:latest image (e9e297452ea6)"
time="2025-03-22T18:26:29Z" level=info msg="Session done" Failed=0 Scanned=26 Updated=1 notify=no
```

### Additional context

The compose.yaml of the container caddy:
```
---
services:
  caddy:
    build:
      context: .
    container_name: caddy
    pull_policy: build
    restart: unless-stopped
    user: "3012:3012"
    cap_add:
      - NET_ADMIN
    env_file:
      - ./secrets.env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./config:/config:rw
      - ./data:/data:rw
      - ./srv:/srv
      - /mnt/logs/caddy/:/logs
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
```
Dockerfile of container caddy:
```
# FROM caddy:2.9.1-builder AS builder
FROM caddy:builder AS builder

RUN xcaddy build \
	--with github.com/caddy-dns/dynu \
	--with github.com/caddy-dns/duckdns

# FROM caddy:2.9.1
FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

compose.yaml of container watchtower:
```
---
services:
  watchtower:
    image: beatkind/watchtower:latest
    container_name: watchtower
    deploy:
      resources:
        limits:
          memory: 128M
    restart: unless-stopped

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./secrets.env
      - ./email.env
    environment:
      - TZ=Europe/London
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_LABEL_ENABLE=false
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_TIMEOUT=300
      - WATCHTOWER_SCHEDULE=0 26 */6 * * *
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=rocker
      - WATCHTOWER_NOTIFICATIONS=email
    labels:
      - "com.centurylinklabs.watchtower.monitor-only=true"
```
