### ISSUE TITLE
specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43

### ISSUE THREAD

**Issue by bogdans92** [beatkind/watchtower#132]
### Describe the bug

Docker container doesn't get rebuilt after new image gets pulled.

### Steps to reproduce

Normal process.

### Expected behavior

Re-build & start (if applicable) the docker container

### Environment

- Platform: Synology 7.2.2 72806
- Architecture: x64
- Docker Version: 24.0.2 , API version 1.43, Go version go1.20.4
- Synology container manager version 24.0.2.... synology......

### Your logs

```text
E-mail logs:
Found new ghcr.io/flmorg/cleanuperr:latest image (9a853d2b581f)
Found new ghcr.io/homarr-labs/homarr:latest image (4fdac016d9dd)
Found new netdata/netdata:latest image (704f9dcab0cb)
Found new lscr.io/linuxserver/nzbget:latest image (9970b2aaf0c6)
Found new grafana/grafana:latest image (5c42a1c2e40b)
Found new lscr.io/linuxserver/kometa:latest image (daa576db83d1)
Found new sctx/overseerr:latest image (01ef727c8412)
Stopping /overseerr (8885dd093747) with SIGTERM
Creating /overseerr
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /kometa
Stopping /syno-monitoring-grafana (18ad1c2b85d8) with SIGTERM
Creating /syno-monitoring-grafana
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /nzbget
Creating /netdata
Stopping /homarrv1 (1679feaec354) with SIGTERM
Creating /homarrv1 
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Stopping /cleanuperr-cleanuperr-1 (07ff09fefddb) with SIGTERM
Creating /cleanuperr-cleanuperr-1
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Removing image aa086f9572b7
Removing image 7599eacf52a5
Removing image b949590e0506
```

### Additional context

Attached also the debug in csv format as this is the only way it let me export.

I checked a bit the debug logs but nothing stands out, i think its the damn synology again.....

Thanks again for all the help in keeping this piece of software alive Jan !

Please let me know if i can provide more details

[watchtower_debug.csv](https://github.com/user-attachments/files/19516128/watchtower_debug.csv)

**Comment by beatkind** [comment]
@bogdans92 by "built" you mean re-created, right?

---
Side note:

> "specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43

Can be fixed with the following argument set to 1.43:

```bash
Argument: --api-version, -a
Environment Variable: DOCKER_API_VERSION
Type: String
Default: "1.44"
```

**Comment by bogdans92** [comment]
Hello, yes, by built i ment once it was upgraded the docker container doesn't get re-created.

Unfortunately i already have the environment variable set, if i don't have it it goes into a crashing loop.

This is the compose file that i use:

Docker compose file:
version: "3"
services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: beatkind/watchtower:latest
    environment:
      WATCHTOWER_NOTIFICATIONS: "email"
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: 
      WATCHTOWER_NOTIFICATION_EMAIL_TO: 
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER:
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: 
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: 
      # WATCHTOWER_LABEL_ENABLE: "true"
      # every day at 6 am
      #WATCHTOWER_SCHEDULE: 0 0 6 * * *
      # testing 
     # WATCHTOWER_SCHEDULE: "*/6 * * * *"
      # every monday at 6 am
      WATCHTOWER_SCHEDULE: 0 0 6 * * 1
      TZ: 'Europe/Bucharest'
      WATCHTOWER_CLEANUP: "true" 
      DOCKER_API_VERSION: "1.43"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_DEBUG: "true"
     # DOCKER_HOST: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

Any other suggestions by chance?

**Comment by DaFlowah** [comment]
Hi there,

I've got the very same issue yesterday when updates have been applied.
I had to recreate the containers starting from the compose file.
This is my stack:
```
version: "2"
services:
  watchtower:
    image: beatkind/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/localtime:/etc/localtime:ro
    environment:
        - WATCHTOWER_NOTIFICATIONS=email
        - WATCHTOWER_NOTIFICATION_EMAIL_FROM=***********
        - WATCHTOWER_NOTIFICATION_EMAIL_TO==***********
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER==***********
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER==***********
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD==***********
        - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=*****
        - WATCHTOWER_SCHEDULE=* 30 20 * * SUN
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_TIMEOUT=30s
        - WATCHTOWER_NOTIFICATIONS_LEVEL=info
        - WATCHTOWER_NO_STARTUP_MESSAGE=true
        - TZ=Europe/Paris
        - DOCKER_API_VERSION=1.43
    networks:
        default:

networks:
    default:
        external: 
            name: rete
```

Unfortunately, I don't have debug logs.
I temporarily reverted to _containrrr_ image.

Email received:
```
Found new portainer/portainer-ce:latest image (fab249e1b82c)
Found new [ghcr.io/gethomepage/homepage:latest](http://ghcr.io/gethomepage/homepage:latest) image (bc3a1d983aab)
Found new [lscr.io/linuxserver/tautulli:latest](http://lscr.io/linuxserver/tautulli:latest) image (7db9216bdc18)
Found new linuxserver/swag:latest image (d9301e5f31bf)
Found new [lscr.io/linuxserver/syncthing:latest](http://lscr.io/linuxserver/syncthing:latest) image (1c4639fee3f2)
Found new vabene1111/recipes:latest image (e030feb15d0b)
Found new [lscr.io/linuxserver/plex:latest](http://lscr.io/linuxserver/plex:latest) image (a477cfc188b6)
Found new yobasystems/alpine-mariadb:latest image (d791a3efd316)
Stopping /fireflyiiidb (8aecb4b97b90) with SIGTERM
Stopping /plex (fd7dbfb6b19e) with SIGTERM
Stopping /recipes-app (1a70f097624a) with SIGTERM
Stopping /syncthing (ae7c91834a65) with SIGTERM
Stopping /nginx-swag (9b1ac4214b34) with SIGTERM
Stopping /tautulli (d32be2315381) with SIGTERM
Stopping /homepage (9fc7fb436e48) with SIGTERM
Stopping /portainer (e43b4f381631) with SIGTERM
Creating /portainer
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /homepage
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /tautulli
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /nginx-swag
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /syncthing
Creating /recipes-app
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /plex
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Creating /fireflyiiidb
"specify mac-address per network" requires API version 1.44, but the Docker daemon API version is 1.43
Removing image 77737b3b8672
```

Somehow, only _syncthing_ survived 🤣

- Model: Synology DS918+
- OS: DSM 7.2.2 72806
- Architecture: x64
- Docker Version: 24.0.2 , API version 1.43, Go version go1.20.4 (two years old version)
- Synology's Container Manager version: 24.0.2-1535
