### ISSUE TITLE
Container starts wirh old image

### ISSUE THREAD

**Issue by icodetea** [beatkind/watchtower#152]
### Describe the bug

I have with booksatck some really creepy behaviour, see logs:

my bookstack db container. 

- it finds a new image, 
- logs that container is stopped and recreated: does not look like he actually does so, I see container still running on old image, created on 2025-04-16 04:31:16
- still removes the image and logs successful update
- since the container is still running with the old removed image he complains next start that he cannot get image details. makes sence, the image is removed.

I see that there is actual a new image in my evvironment. somehow he did not managed to successful recreate a new container with this image. any idea whats going on here?

I may consider it debug by myself and contribute a patch but maybe someone else is more familiar with the code and behavior and can give me hints?

### Expected behavior

should actually recreate container with new image

### Environment

`dockeruser@DockerStation:~$ docker version
Client: Docker Engine - Community
 Version:           28.1.1
 API version:       1.49
 Go version:        go1.23.8
 Git commit:        4eba377
 Built:             Fri Apr 18 09:52:57 2025
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          28.1.1
  API version:      1.49 (minimum version 1.24)
  Go version:       go1.23.8
  Git commit:       01f442b
  Built:            Fri Apr 18 09:52:57 2025
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.27
  GitCommit:        05044ec0a9a75232cad458027ca83437aae3f4da
 runc:
  Version:          1.2.5
  GitCommit:        v1.2.5-0-g59923ef
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
dockeruser@DockerStation:~$ uname -a
Linux DockerStation 6.1.0-33-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.133-1 (2025-04-10) x86_64 GNU/Linux
`

### Your logs

```text
time="2025-04-23T04:30:21+02:00" level=info msg="Found new lscr.io/linuxserver/mariadb:latest image (33c279065dff)"
time="2025-04-23T04:30:41+02:00" level=info msg="Stopping /bookstack_db (6b5f31e6c31d) with SIGTERM"
time="2025-04-23T04:30:50+02:00" level=info msg="Creating /bookstack_db"
time="2025-04-23T04:30:54+02:00" level=info msg="Removing image 01d815a7d46a"
time="2025-04-23T04:30:55+02:00" level=info msg="Session done" Failed=0 Scanned=31 Updated=1 notify=no
...
time="2025-04-27T09:22:24+02:00" level=warning msg="Failed to retrieve container image info: Error response from daemon: No such image: sha256:01d815a7d46a7fe816cb714f2cc0ed6edab67286e37640633bd57cc4e76f1589"


dockeruser@DockerStation:~$ docker container ls | grep bookstack_db
7a05a23ad14d   01d815a7d46a                                         "/init"                  11 days ago      Up 11 hours (healthy)     3306/tcp                                                                                                                                                                             bookstack_db
dockeruser@DockerStation:~$ docker image ls | grep maria
lscr.io/linuxserver/mariadb                  latest        33c279065dff   5 days ago      343MB
dockeruser@DockerStation:~$ docker image ls | grep 01d815a7d46a
```

**Comment by beatkind** [comment]
@icodetea did this happened once or are you able to replicate it?

**Comment by icodetea** [comment]
this happens regularly, each new image. but only on this specific stack. I wonder what is so special here

**Comment by icodetea** [comment]
I also can share the compose of this stack, nothing special here:
```

services:
  app:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack_app
    environment:
      - PUID=1000
      - PGID=114
      - TZ=${TIMEZONE}
      - APP_URL=${APP_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
    volumes:
      - bookstack_data:/config
    ports:
      - 6875:80
    networks:
      - network
    restart: unless-stopped
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost/status"]
      interval: 10s
      timeout: 5s
      retries: 3
  db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=114
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - bookstack_db:/config
      - db_backup:/sql_backup
    networks:
      - network
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "mysql --help"]
      interval: 10s 
      timeout: 5s 
      retries: 3
    restart: unless-stopped
volumes:
  bookstack_data:
    external: true
  bookstack_db:
    external: true
  db_backup:
networks:
  network:
  db_network:
    external: true

```
