### ISSUE TITLE
WATCHTOWER_POLL_INTERVAL and WATCHTOWER_HTTP_API_TOKEN set, curl /v1/update returns a 404

### ISSUE THREAD

**Issue by divStar** [beatkind/watchtower#162]
### Describe the bug

I set up `beatkind/watchtower` using this `docker-compose.yml`:

<details><summary><code>docker-compose.yml</code></summary>

```yaml
networks:
  default:
    name: services-network
    external: true

services:
  watchtower:
    image: beatkind/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --http-api-periodic-polls
    ports:
      - "3080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ
      # Configure watchtower
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_HTTP_API_TOKEN=a14d1749-a30f-4c48-9c20-ab629d3bd1ec
      - WATCHTOWER_HTTP_API_METRICS=true
      # Configure notification via e-mail
      - WATCHTOWER_NOTIFICATIONS
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM
      - WATCHTOWER_NOTIFICATION_EMAIL_TO
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD
      - WATCHTOWER_NOTIFICATION_EMAIL_DELAY
```
(I omitted the notification values here)
</details>

It starts up properly and outputs this:
```shell
time="2025-06-05T01:10:35+02:00" level=info msg="Watchtower 2.3.1" notify=no
time="2025-06-05T01:10:35+02:00" level=info msg="Using notifications: smtp" notify=no
time="2025-06-05T01:10:35+02:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no
time="2025-06-05T01:10:35+02:00" level=info msg="Scheduling first run: 2025-06-06 01:10:35 +0200 CEST" notify=no
time="2025-06-05T01:10:35+02:00" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds" notify=no
```

However: while
```shell
curl -H "Authorization: Bearer a14d1749-a30f-4c48-9c20-ab629d3bd1ec" http://<host>:3080/v1/metrics
```
works, the update endpoint returns a 404 (`404 page not found` to be precise):
```shell
curl -H "Authorization: Bearer a14d1749-a30f-4c48-9c20-ab629d3bd1ec" http://<host>:3080/v1/update
```
I have not yet found what the issue is - perhaps it's the dashes in the UUID though (will check).

Does anyone know why it might be not working?

### Steps to reproduce

1. Install the `docker-compose.yml` (adjust the network to fit your environment).
2. Attempt to use `curl` with the proper bearer token on the `/v1/update` endpoint while also using `command: --http-api-periodic-polls` to keep the poll intervals going.
3. See error (`404 page not found`).

### Expected behavior

The update process should start.

### Environment

- Platform: x86-64
- Architecture: AMD64
- Docker Version: v27.5.0 Standalone

### Your logs

```text
time="2025-06-05T01:10:35+02:00" level=info msg="Watchtower 2.3.1" notify=no

time="2025-06-05T01:10:35+02:00" level=info msg="Using notifications: smtp" notify=no

time="2025-06-05T01:10:35+02:00" level=info msg="Checking all containers (except explicitly disabled with label)" notify=no

time="2025-06-05T01:10:35+02:00" level=info msg="Scheduling first run: 2025-06-06 01:10:35 +0200 CEST" notify=no

time="2025-06-05T01:10:35+02:00" level=info msg="Note that the first check will be performed in 23 hours, 59 minutes, 59 seconds" notify=no
```

### Additional context

I am using Portainer on TrueNAS 25.04 to deploy the `docker-compose.yml` file of Watchtower - not sure if this matters though. The network (`services-network` in my example) does exist and is IPv4-only and I generally did everything I could to turn off IPv6 in TrueNAS 25.04 (including setting the global Sysctl property).

In fact using `curl` with the direct server (host) IPv4 address yields the same result.
