### ISSUE TITLE
volume subpath of compose file is not honored

### ISSUE THREAD

**Issue by janusn** [beatkind/watchtower#78]
### Describe the bug

I have switched from [containrrr/watchtower](https://github.com/containrrr/watchtower) to this fork as the containrrr/watchtower has not been updated for a year.

This is a bug that forces me to try alternatives.

For containers created with compose, the volume subpath is not honored when recreating the container.

e.g. for the following compose.yaml:
```
---
services:
  homeassistant:
    image: linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1017
      - PGID=1017
      - TZ=Europe/London
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config:rw"
      - type: volume
        source: cctv
        target: /config/nest
        volume:
          subpath: ha/nest
    restart: unless-stopped

volumes:
  cctv:
    name: homeassistant_cctv
    driver: local
    driver_opts:
      type: cifs
      o: "addr=10.2.3.4,\
        username=user,\
        password=password,\
        file_mode=0660,\
        dir_mode=0770,\
        uid=1017,\
        gid=1017,\
        rw,\
        vers=3.0,\
        auto,\
        noserverino"
      device: "//10.2.3.4/cctv"
```

When watchertower pulled a new image and recreated the container, the directory `/config/nest` in the container is mapped to `smb://10.2.3.4/cctv` instead of `smb://10.2.3.4/cctv/ha/nest`.

### Steps to reproduce

1. create a container based on the above compose.yaml file
2. wait for watchtower update the image
3. check the the volume inside the container.

### Expected behavior

The services/volumes/subpath argument is honored by the updated container.

### Environment

- Platform: Ubuntu Server 24.04.1
- Architecture: 13th Gen Intel(R) Core(TM) i5-1340P, 16 cores
- Docker Version: 26.1.4, build 5650f9b

### Your logs

```text
time="2024-08-23T05:16:06+01:00" level=info msg="Session done" Failed=0 Scanned=10 Updated=0 notify=no
time="2024-08-24T05:16:10+01:00" level=info msg="Found new linuxserver/swag:latest image (5e517efa86fa)"
time="2024-08-24T05:16:12+01:00" level=info msg="Stopping /swag (e5a749b68a8d) with SIGTERM"
time="2024-08-24T05:16:14+01:00" level=info msg="Creating /swag"
time="2024-08-24T05:16:14+01:00" level=info msg="Removing image e8fc40a76ba1"
time="2024-08-24T05:16:14+01:00" level=info msg="Session done" Failed=0 Scanned=10 Updated=1 notify=no
time="2024-08-25T05:16:08+01:00" level=info msg="Found new teddysun/v2ray:latest image (90428c02fcf3)"
time="2024-08-25T05:16:09+01:00" level=info msg="Stopping /v2ray (bb0b34fefb17) with SIGTERM"
time="2024-08-25T05:16:10+01:00" level=info msg="Creating /v2ray"
time="2024-08-25T05:16:10+01:00" level=info msg="Removing image fa97e3109e18"
time="2024-08-25T05:16:10+01:00" level=info msg="Session done" Failed=0 Scanned=10 Updated=1 notify=no
time="2024-08-26T05:16:29+01:00" level=info msg="Found new linuxserver/homeassistant:latest image (4824f0437bce)"
time="2024-08-26T05:16:33+01:00" level=info msg="Stopping /homeassistant (6853f16d79fb) with SIGTERM"
time="2024-08-26T05:16:35+01:00" level=info msg="Creating /homeassistant"
time="2024-08-26T05:16:36+01:00" level=info msg="Removing image 12289b32df4e"
time="2024-08-26T05:16:38+01:00" level=info msg="Session done" Failed=0 Scanned=10 Updated=1 notify=no
time="2024-08-27T05:16:06+01:00" level=info msg="Session done" Failed=0 Scanned=10 Updated=0 notify=no
time="2024-08-28T05:16:24+01:00" level=info msg="Found new linuxserver/homeassistant:latest image (266f3481775d)"
time="2024-08-28T05:16:30+01:00" level=info msg="Stopping /homeassistant (cd410b001528) with SIGTERM"
time="2024-08-28T05:16:32+01:00" level=info msg="Creating /homeassistant"
time="2024-08-28T05:16:32+01:00" level=info msg="Removing image 4824f0437bce"
time="2024-08-28T05:16:34+01:00" level=info msg="Session done" Failed=0 Scanned=10 Updated=1 notify=no
```
